INSERT INTO team (idteam, idapi, name, logo) VALUES (1, 44, "Burnley", "https://media.api-sports.io/football/teams/44.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (2, 33, "Manchester United", "https://media.api-sports.io/football/teams/33.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (3, 52, "Crystal Palace", "https://media.api-sports.io/football/teams/52.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (4, 41, "Southampton", "https://media.api-sports.io/football/teams/41.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (5, 36, "Fulham", "https://media.api-sports.io/football/teams/36.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (6, 42, "Arsenal", "https://media.api-sports.io/football/teams/42.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (7, 40, "Liverpool", "https://media.api-sports.io/football/teams/40.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (8, 63, "Leeds", "https://media.api-sports.io/football/teams/63.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (9, 50, "Manchester City", "https://media.api-sports.io/football/teams/50.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (10, 66, "Aston Villa", "https://media.api-sports.io/football/teams/66.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (11, 47, "Tottenham", "https://media.api-sports.io/football/teams/47.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (12, 45, "Everton", "https://media.api-sports.io/football/teams/45.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (13, 60, "West Brom", "https://media.api-sports.io/football/teams/60.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (14, 46, "Leicester", "https://media.api-sports.io/football/teams/46.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (15, 48, "West Ham", "https://media.api-sports.io/football/teams/48.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (16, 34, "Newcastle", "https://media.api-sports.io/football/teams/34.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (17, 51, "Brighton", "https://media.api-sports.io/football/teams/51.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (18, 49, "Chelsea", "https://media.api-sports.io/football/teams/49.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (19, 62, "Sheffield Utd", "https://media.api-sports.io/football/teams/62.png");
INSERT INTO team (idteam, idapi, name, logo) VALUES (20, 39, "Wolves", "https://media.api-sports.io/football/teams/39.png");


INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (1, 2725, "Community Shield", "https://media.api-sports.io/football/leagues/528.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (2, 2745, "FA WSL", "https://media.api-sports.io/football/leagues/44.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (3, 2781, "League Cup", "https://media.api-sports.io/football/leagues/48.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (4, 2790, "Premier League", "https://media.api-sports.io/football/leagues/39.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (5, 2791, "FA Cup", "https://media.api-sports.io/football/leagues/45.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (6, 2792, "EFL Trophy", "https://media.api-sports.io/football/leagues/46.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (7, 2794, "Championship", "https://media.api-sports.io/football/leagues/40.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (8, 2796, "League Two", "https://media.api-sports.io/football/leagues/42.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (9, 2800, "FA Trophy", "https://media.api-sports.io/football/leagues/47.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (10, 2803, "League One", "https://media.api-sports.io/football/leagues/41.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (11, 2830, "Non League Div One - Isthmian North", "https://media.api-sports.io/football/leagues/52.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (12, 2831, "Non League Premier - Southern", "https://media.api-sports.io/football/leagues/60.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (13, 2836, "Community Shield Women", "https://media.api-sports.io/football/leagues/670.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (14, 2879, "Non League Div One - Isthmian South", "https://media.api-sports.io/football/leagues/53.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (15, 2880, "Non League Div One - Northern North", "https://media.api-sports.io/football/leagues/54.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (16, 2881, "Non League Div One - Northern South", "https://media.api-sports.io/football/leagues/55.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (17, 2882, "Non League Div One - Southern Central", "https://media.api-sports.io/football/leagues/56.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (18, 2883, "Non League Div One - Southern SW", "https://media.api-sports.io/football/leagues/57.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (19, 2884, "Non League Premier - Isthmian", "https://media.api-sports.io/football/leagues/58.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (20, 2885, "Non League Premier - Northern", "https://media.api-sports.io/football/leagues/59.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (21, 2942, "National League", "https://media.api-sports.io/football/leagues/43.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (22, 2943, "National League - North", "https://media.api-sports.io/football/leagues/50.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (23, 2944, "National League - South", "https://media.api-sports.io/football/leagues/51.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (24, 3011, "U18 Premier League - North", "https://media.api-sports.io/football/leagues/695.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (25, 3012, "U18 Premier League - South", "https://media.api-sports.io/football/leagues/696.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (26, 3013, "WSL Cup", "https://media.api-sports.io/football/leagues/697.png", 1);
INSERT INTO league (idleague, idapi, name, logo, idcountry) VALUES (27, 3015, "Women's Championship", "https://media.api-sports.io/football/leagues/699.png", 1);
